# ----------------------------------------
#  App Title: Benford's Law and Sequences
#     Author: Jimmy Doi
# ----------------------------------------
library(shinyIncubator)

shinyUI(navbarPage("Benford's Law: Sequences",

###################################################################################################
## tabPanel: Additive Sequence                                                                   ##
###################################################################################################
tabPanel("(1) Additive Sequence",
   fluidPage(    
       tags$head(tags$link(rel = "icon", type = "image/x-icon", href = 
       "https://webresource.its.calpoly.edu/cpwebtemplate/5.0.1/common/images_html/favicon.ico")),  

       progressInit(),
                              
       # Give the page a title
       h3("Benford's Law: Additive Sequence"),

        div("Note: Please adjust width of browser if only one column is visible.",br(),
            HTML("<a href='http://shiny.stat.calpoly.edu/BenfordData' style='color:    #DC143C'
            target='_blank'>[Click here for another Shiny app on Benford's Law]</a>"), 
            style = "font-size: 9pt;color:teal"),br(),
       
       p("Consider a sequence of numbers where we fix the initial two numbers and then the
         value of each subsequent number is the sum of the previous two. We will call this an",
         tags$b("additive sequence."),
         "When the initial two numbers are both 1 then this yields the famous Fibonacci sequence. 
         If you only consider the first digit of each number in an additive sequence and examine its distribution,
         is it the case that it closely follows ", 
         HTML("<a href='http://mathworld.wolfram.com/BenfordsLaw.html', target='_blank'>Benford's Law</a>?"), 
         "This app generates an additive sequence, for a given length and initial sequence numbers, 
         and applies a goodness of fit test of the observed frequencies of first digits to Benford's Law",
         style="font-size:11pt"),
       HTML("<hr style='height: 2px; color: #BDBDBD; background-color: #D9D9D9; border: none;'>"),
       
       # Generate a row with a sidebar
       fluidRow(      
         
         column(4,wellPanel(
           
           sliderInput("seq1", 
                       label = h5("First Sequence Number"),
                       min = 1, max = 9, value = 1, step=1),br(),
           
           sliderInput("seq2", 
                       label = h5("Second Sequence Number"),
                       min = 1, max = 9, value = 1, step=1),br(),
           
           sliderInput("length", 
                       label = h5(HTML("Length of sequence (<i>n</i>)")),
                       min = 150, max = 1000, value = 150, step=50),br(),
           
           br(), br(), br(), br(), 
           
           div("Shiny app by", 
               a(href="http://statweb.calpoly.edu/jdoi/",target="_blank", 
                 "Jimmy Doi"),align="right", style = "font-size: 8pt"),
           
           div("Base R code by", 
               a(href="http://statweb.calpoly.edu/jdoi/",target="_blank", 
                 "Jimmy Doi"),align="right", style = "font-size: 8pt"),
           
           div("Shiny source files:",
               a(href="https://gist.github.com/calpolystat/f4475cbfe4cc77cef168",
                 target="_blank","GitHub Gist"),align="right", style = "font-size: 8pt"),
           
           div(a(href="http://www.statistics.calpoly.edu/shiny",target="_blank", 
                 "Cal Poly Statistics Dept Shiny Series"),align="right", style = "font-size: 8pt")
         )),
         column(8,
          div(span(tags$b("First 50 numbers in the sequence (first digit in"),style="font-size:9pt"),
              span(
                span("red",style="font-size:9pt; color:red; font-weight:bold"),tags$b("):",
                conditionalPanel("input.seq1==1 & input.seq2==1", 
                  span(HTML("&nbsp;&nbsp;&nbsp;"),"[Fibonacci sequence]",
                  style="text-align: right;color:blue;font-size:9pt;display:inline-block"),
                  style="text-align: right;font-size:0pt;display:inline-block;"),                                        
                conditionalPanel("input.seq1==2 & input.seq2==1",
                  span(HTML("&nbsp;&nbsp;&nbsp;"),"[Lucas sequence]",
                  style="text-align: right;color:blue;font-size:9pt;display:inline-block"),
                  style="text-align: right;font-size:0pt;display:inline-block;"),style="font-size:9pt")),
              style="font-size:0pt"),
          div(
            div(span(textOutput("num.1a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.1b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.2a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.2b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.3a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.3b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.4a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.4b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.5a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.5b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.6a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.6b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.7a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.7b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.8a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.8b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.9a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.9b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.10a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.10b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.11a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.11b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.12a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.12b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.13a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.13b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.14a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.14b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.15a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.15b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.16a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.16b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.17a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.17b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.18a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.18b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.19a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.19b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.20a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.20b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.21a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.21b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.22a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.22b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.23a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.23b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.24a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.24b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.25a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.25b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.26a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.26b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.27a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.27b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.28a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.28b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.29a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.29b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.30a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.30b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.31a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.31b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.32a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.32b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.33a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.33b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.34a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.34b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.35a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.35b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.36a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.36b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.37a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.37b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.38a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.38b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.39a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.39b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.40a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.40b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.41a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.41b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.42a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.42b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.43a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.43b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.44a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.44b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.45a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.45b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.46a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.46b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.47a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.47b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.48a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.48b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.49a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.49b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                style="display:inline-block"),
            div(span(textOutput("num.50a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
                span(textOutput("num.50b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
                span("",style="font-size: 9pt"),style="display:inline-block"),
            style="font-size:0;"),
          
          div(span("[Sequence has ",style="text-align: right;font-size:9pt;display:inline-block"),
              span(HTML("&nbsp;"),style="text-align: right;font-size:9pt"),
              span(textOutput("textlength"),style="text-align: right;font-size:9pt;display:inline-block;color:teal"),
              span(HTML("&nbsp;"),style="text-align: right;font-size:9pt"),
              span("numbers total]",style="text-align: right;font-size:9pt;display:inline-block"),
                                                         style="text-align: right;font-size:0pt;display:inline-block;"),
          
          HTML("<hr style='height: 2px; color: #de7008; background-color: #df7109; border: none;'>"),
          
          fluidRow(
            column(4,
                   p(tags$b("Goodness of Fit Test")),
                   verbatimTextOutput("goodness")),
            column(8,
                   plotOutput("pmf")
            )#closes column-8
          ),#closes fluidRow
          HTML("<hr style='height: 2px; color: #de7008; background-color: #df7109; border: none;'>")
       ) # closes column-8
    ) #closes fluidRow
  ) #closes fluidPage
), #close tabPanel#1

###################################################################################################
## tabPanel: Power Sequence                                                                     ##
###################################################################################################
tabPanel("(2) Power Sequence",
  fluidPage(    
           
  # Give the page a title
  h3("Benford's Law: Power Sequence"),
           
  div("Note: Please adjust width of browser if only one column is visible.",br(),
  HTML("<a href='https://calpolystat.shinyapps.io/BenfordData',
            target='_blank'>[Click here for another Shiny app on Benford's Law]</a>"), 
      style = "font-size: 9pt;color:teal"),br(),
  
  p("Consider a sequence of the form", 
  HTML("<i>b<sup>1</sup></i>, <i>b<sup>2</sup></i>, &hellip;, <i>b<sup>&nbsp;n</sup></i>, "),
  "where ", tags$em("b"), "is called the base. 
  We will call this a ", HTML("<b>power sequence</b>."), "
  If you only consider the first digit of each number in a power sequence and examine its distribution,
  is it the case that it closely follows ", 
  HTML("<a href='http://mathworld.wolfram.com/BenfordsLaw.html', target='_blank'>Benford's Law</a>?"), 
    "This app generates the power sequence, for a given", HTML("<i>b</i> and <i>n</i>,"), 
    "and applies a goodness of fit test of the observed frequencies of first digits to Benford's Law.",
    style="font-size:11pt"),
  HTML("<hr style='height: 2px; color: #BDBDBD; background-color: #D9D9D9; border: none;'>"),
  
  fluidRow(      
    
    column(4,wellPanel(
      
      sliderInput("pow.base", 
                  label = h5(HTML("Base value (<i>b</i>)")),
                  min = 2, max = 9, value = 2, step=1),br(),
      
      sliderInput("pow.length", 
                  label = h5(HTML("Length of sequence (<i>n</i>)")),
                  min = 150, max = 300, value = 150, step=10),br(),
      
      br(), br(), br(), br(), 
      
      div("Shiny app by", 
          a(href="http://statweb.calpoly.edu/jdoi/",target="_blank", 
            "Jimmy Doi"),align="right", style = "font-size: 8pt"),
      
      div("Base R code by", 
          a(href="http://statweb.calpoly.edu/jdoi/",target="_blank", 
            "Jimmy Doi"),align="right", style = "font-size: 8pt"),
      
      div("Shiny source files:",
          a(href="https://gist.github.com/calpolystat/f4475cbfe4cc77cef168",
            target="_blank","GitHub Gist"),align="right", style = "font-size: 8pt"),
      
      div(a(href="http://www.statistics.calpoly.edu/shiny",target="_blank", 
            "Cal Poly Statistics Dept Shiny Series"),align="right", style = "font-size: 8pt")
    )),
    column(8,
      div(span(tags$b("First 20 numbers in the sequence (first digit in"),style="font-size:9pt"),
          span(
            span("red",style="font-size:9pt; color:red; font-weight:bold"),tags$b("):",style="font-size:9pt")),
          style="font-size:0pt"),
      div(
        div(span(textOutput("e.num.1a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.1b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            style="display:inline-block"),
        div(span(textOutput("e.num.2a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.2b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            style="display:inline-block"),
        div(span(textOutput("e.num.3a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.3b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            style="display:inline-block"),
        div(span(textOutput("e.num.4a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.4b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            style="display:inline-block"),
        div(span(textOutput("e.num.5a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.5b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            style="display:inline-block"),
        div(span(textOutput("e.num.6a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.6b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            style="display:inline-block"),
        div(span(textOutput("e.num.7a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.7b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            style="display:inline-block"),
        div(span(textOutput("e.num.8a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.8b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            style="display:inline-block"),
        div(span(textOutput("e.num.9a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.9b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            style="display:inline-block"),
        div(span(textOutput("e.num.10a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.10b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            style="display:inline-block"),
        div(span(textOutput("e.num.11a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.11b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            style="display:inline-block"),
        div(span(textOutput("e.num.12a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.12b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            style="display:inline-block"),
        div(span(textOutput("e.num.13a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.13b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            style="display:inline-block"),
        div(span(textOutput("e.num.14a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.14b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            style="display:inline-block"),
        div(span(textOutput("e.num.15a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.15b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            style="display:inline-block"),
        div(span(textOutput("e.num.16a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.16b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            style="display:inline-block"),
        div(span(textOutput("e.num.17a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.17b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            style="display:inline-block"),
        div(span(textOutput("e.num.18a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.18b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            style="display:inline-block"),
        div(span(textOutput("e.num.19a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.19b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            style="display:inline-block"),
        div(span(textOutput("e.num.20a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
            span(textOutput("e.num.20b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
            span("",style="font-size: 9pt"),style="display:inline-block"),
        style="font-size:0;"),
      div(span("[Sequence has ",style="font-size:9pt;display:inline-block"),
          span(HTML("&nbsp;"),style="font-size:9pt"),
          span(textOutput("powlength"),style="font-size:9pt;display:inline-block;color:teal"),
          span(HTML("&nbsp;"),style="font-size:9pt"),
          span("numbers total]",style="font-size:9pt;display:inline-block"),style="font-size:0pt;display:inline-block;",align="right"),
      
      HTML("<hr style='height: 2px; color: #de7008; background-color: #df7109; border: none;'>"),
      fluidRow(
        column(4,
               p(tags$b("Goodness of Fit Test")),
               verbatimTextOutput("e.goodness")),
        column(8,
               plotOutput("e.pmf")
              ) #closes column-8
            ), #closes fluidRow
          HTML("<hr style='height: 2px; color: #de7008; background-color: #df7109; border: none;'>")
        ) #closes column-8
     ) #closes fluidRow
  ) #closes fluidPage
), #close tabPanel#2

###################################################################################################
## tabPanel: Prime Numbers Sequence                                                              ##
###################################################################################################
tabPanel("(3) Prime Numbers Sequence",
  fluidPage(    
    
    # Give the page a title
    h3("Generalized Benford's Law: Prime Numbers Sequence"),
    
    div("Note: Please adjust width of browser if only one column is visible.",br(),
        HTML("<a href='https://calpolystat.shinyapps.io/BenfordData',
              target='_blank'>[Click here for another Shiny app on Benford's Law]</a>"), 
        style = "font-size: 9pt;color:teal"),br(),
    
    
    p("Consider the sequence of prime numbers less than or equal to some power of 10. An article from 2009
      shows that the distribution of the first digit of these prime numbers
      is well described by what's known as", HTML("<b>Generalized Benford's Law (GBL)</b>"),".
      This app generates the prime numbers less than or equal to", HTML("10<sup>3</sup>, 10<sup>4</sup>, 
      10<sup>5</sup>, or 10<sup>6</sup>"), "and applies a goodness of fit test of the observed frequencies of first digits to GBL."
      ),
    
    p("More information on the Generalized Benford's Law can be found in the following journal article:"),
    
    div("Luque, B. and Lacasa, L.(2009)",
        HTML("'<a href='http://rspa.royalsocietypublishing.org/content/465/2107/2197.abstract?sid=25124ad9-160f-432e-afe9-17b04ae725d1',
        target='_blank'>The first-digit frequencies of prime numbers and Riemann zeta zeros</a>'"), 
        em("Proc. R. Soc. A"),", 465, 2197-2216", style="padding-left: 20px; display:block; border-left: 5px solid #faebbc;margin-left:0px"),
    
    HTML("<hr style='height: 2px; color: #BDBDBD; background-color: #D9D9D9; border: none;'>"),

    # Generate a row with a sidebar
    fluidRow(      
      
      column(4,wellPanel(
      
        selectInput("my.n", label = h5("Generate sequence of prime numbers less than or equal to"), 
                    choices = list("1,000" = 1000, "10,000" = 10000, "100,000" = 100000, "1,000,000" = 1000000), 
                    selected = 1000),
        
        br(), br(), br(), br(), 
        
        div("Shiny app by", 
            a(href="http://statweb.calpoly.edu/jdoi/",target="_blank", 
              "Jimmy Doi"),align="right", style = "font-size: 8pt"),
        
        div("Base R code by", 
            a(href="http://statweb.calpoly.edu/jdoi/",target="_blank", 
              "Jimmy Doi"),align="right", style = "font-size: 8pt"),
        
        div("Shiny source files:",
            a(href="https://gist.github.com/calpolystat/f4475cbfe4cc77cef168",
              target="_blank","GitHub Gist"),align="right", style = "font-size: 8pt"),
        
        div(a(href="http://www.statistics.calpoly.edu/shiny",target="_blank", 
              "Cal Poly Statistics Dept Shiny Series"),align="right", style = "font-size: 8pt")
      )),
      column(8,
        div(span(tags$b("First 80 numbers in the sequence (first digit in"),style="font-size:9pt"),
            span(
              span("red",style="font-size:9pt; color:red; font-weight:bold"),tags$b("):",style="font-size:9pt")),
            style="font-size:0pt"),
        div(
          div(span(textOutput("pr.num.1a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.1b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.2a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.2b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.3a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.3b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.4a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.4b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.5a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.5b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.6a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.6b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.7a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.7b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.8a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.8b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.9a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.9b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.10a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.10b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.11a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.11b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.12a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.12b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.13a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.13b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.14a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.14b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.15a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.15b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.16a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.16b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.17a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.17b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.18a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.18b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.19a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.19b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.20a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.20b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.21a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.21b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.22a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.22b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.23a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.23b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.24a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.24b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.25a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.25b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.26a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.26b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.27a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.27b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.28a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.28b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.29a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.29b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.30a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.30b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.31a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.31b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.32a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.32b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.33a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.33b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.34a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.34b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.35a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.35b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.36a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.36b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.37a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.37b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.38a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.38b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.39a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.39b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.40a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.40b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.41a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.41b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.42a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.42b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.43a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.43b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.44a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.44b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.45a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.45b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.46a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.46b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.47a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.47b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.48a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.48b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.49a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.49b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.50a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.50b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.51a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.51b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.52a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.52b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.53a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.53b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.54a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.54b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.55a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.55b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.56a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.56b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.57a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.57b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.58a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.58b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.59a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.59b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.60a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.60b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.61a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.61b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.62a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.62b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.63a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.63b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.64a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.64b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.65a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.65b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.66a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.66b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.67a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.67b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.68a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.68b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.69a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.69b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.70a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.70b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),
          div(span(textOutput("pr.num.71a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.71b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.72a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.72b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.73a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.73b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.74a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.74b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.75a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.75b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.76a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.76b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.77a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.77b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.78a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.78b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.79a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.79b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          div(span(textOutput("pr.num.80a"),style="font-size: 9pt; color:red; font-weight:bold; display:inline-block"),
              span(textOutput("pr.num.80b"),style="font-size: 9pt; color:black; display:inline-block"),span(HTML("&nbsp;"),style="font-size:9pt"),
              style="display:inline-block"),                                         
          style="font-size:0;"),
        div(span("[Sequence has ",style="font-size:9pt;display:inline-block"),
            span(HTML("&nbsp;"),style="font-size:9pt"),
            span(textOutput("num.primes"),style="font-size:9pt;display:inline-block;color:teal"),
            span(HTML("&nbsp;"),style="font-size:9pt"),
            span("prime numbers total]",style="font-size:9pt;display:inline-block"),style="font-size:0pt;display:inline-block;",align="right"),
        
        HTML("<hr style='height: 2px; color: #de7008; background-color: #df7109; border: none;'>"),
        fluidRow(
          column(4,
                 p(tags$b("Goodness of Fit Test")),
                 verbatimTextOutput("pr.goodness")),
          column(8,
                 plotOutput("pr.pmf")
              ) # closes column-8
            ), #closes fluidRow
          HTML("<hr style='height: 2px; color: #de7008; background-color: #df7109; border: none;'>")
        ) #closes column-8
     ) #closes fluidRow
  ) #closes fluidPage
) #closes tabPanel#3
) #closes navbarPage
) #closes shinyUI
