if (!require("shinyBS")) install.packages("shinyBS")

shinyUI(fluidPage(
      tags$head(tags$link(rel = "icon", type = "image/x-icon", href = 
    "https://webresource.its.calpoly.edu/cpwebtemplate/5.0.1/common/images_html/favicon.ico")),  
        navbarPage(title="Hierarchical Models",
                   
                   tabPanel("Goal of Study",
                            column(1),
                            column(5,br(),br(),br(),br(),br(),br(),br(),br(),br(),
                                   p("This study focuses on implementing", code("Hierarchical Models",style="color:navy"), "with nested data and comparing this method to
                                     the", code("Pooled",style="color:navy"), "and", code("Unpooled",style="color:navy"), "method.  The pooled method complete ignores any nesting structure in the data,
                                     which does not account for the variability in the response among the nesting groups.  The unpooled method overstates the
                                     variability among the nesting groups by fitting separate estimates for each nesting group without taking into 
                                     account information from other groups.  Hierarchical models serve as a balance between these two methods.
                                     It accounts for the variability in the nesting groups while fitting group estimates by using information
                                     across all the groups.")),
                            column(5,br(),br(),br(),br(),br(),br(),br(),br(),br(),
                                   p("Two key related concepts are present:", strong("borrowing strength"), "and", strong("shrinkage"),".  Borrowing strength
                                     refers to how estimates for groups with small sample sizes are pulled toward the average of all groups.  Shrinkage
                                     refers to how estimates from hierarchical models are closer together compared to the unpooled method."),
                                   p(strong("Level 1 observational units (i)"), "refer to the units observed at the lowest level and are nested in groups.",  strong("Level 2
                                     observational units (j)"), "refer to the groups in which the level 1 observational units are nested in.  Predictor at both
                                     levels can be used but the response variable must be at level 1."),
                                   div("Shiny app by", 
                                       a(href="http://www.linkedin.com/in/jimmywong46/",target="_blank","Jimmy Wong"),align="right", style = "font-size: 8pt"),
                                   div("Shiny source files:",
                                       a(href="https://gist.github.com/calpolystat/d896c5848934484181be",
                                         target="_blank","GitHub Gist"),align="right", style = "font-size: 8pt"),
                                   div(a(href="http://www.statistics.calpoly.edu/shiny",target="_blank", 
                                         "Cal Poly Statistics Dept Shiny Series"),align="right", style = "font-size: 8pt")),
                            column(1)),
                   
                   tabPanel("Select Data",
                            tabsetPanel(
                              tabPanel("Sample Data",
                                       column(4,
                                              checkboxInput("usesample", "Use sample data", TRUE),br(),
                                              p("The music data set is from a performance anxiety study conducted by Sadler and Miller (2010).  They collected data on 
                                                37 undergraduate music majors who filled out performance diaries over a whole academic year.  Before each performance,
                                                each musician also completed a Positive Affect Negative Affect Schedule (PANAS), in which two variables were measured: negative
                                                affect (measure of anxiety) and positive affect (measure of happiness).  In total, variables were measured on the musicians and
                                                each of their performances.  This app will focus on how negative affect is associated with characteristics of the musicians and
                                                characteristics of the performances.")),
                                       column(7,
                                              dataTableOutput("sampledata")),
                                       column(1)),
                              tabPanel("Upload Data",
                                       fluidRow(
                                         column(3,
                                                fileInput("file", "",accept=c("text/csv", "text/comma-separated-values,text/plain", ".csv")),
                                                checkboxInput("header", "Header", TRUE),
                                                radioButtons("sep", "Separator:", choices=c(Comma=",",Semicolon=";",Tab="\t"), selected=","),
                                                radioButtons("quote", "Quote", choices=c(None="","Double Quote"='"',"Single Quote"="'"),selected="")),
                                         column(9,
                                                dataTableOutput("datatable")))),
                              tabPanel("Customize Models for Studies",
                                       fluidRow(
                                         column(12,
                                                "Customize models if using uploaded data."),br(),
                                         column(3,
                                                strong("Varying-intercept:"),hr(),
                                                htmlOutput("selectresponse1"),
                                                htmlOutput("selectlevel2id1")),
                                         column(3,
                                                strong("Varying-intercept and varying-slope:"),hr(),
                                                htmlOutput("selectresponse2"),
                                                htmlOutput("selectlevel2id2"),
                                                htmlOutput("selectlevel1pred1")),
                                         column(5,
                                                strong("Varying-intercept and varying-slope with level 2 predictor:"),hr(),
                                                htmlOutput("selectresponse3"),
                                                htmlOutput("selectlevel2id3"),
                                                htmlOutput("selectlevel1pred2"),
                                                htmlOutput("selectlevel2pred1")))))),
#                               tabPanel("Customize Model",
#                                        fluidRow(
#                                          column(4,
#                                                 htmlOutput("selectresponse"),
#                                                 hr(),
#                                                 htmlOutput("selectlevel1fixedpred"),
#                                                 hr(),
#                                                 htmlOutput("selectlevel1randpred")),
#                                          column(4,
#                                                 htmlOutput("selectlevel2id"),
#                                                 hr(),
#                                                 htmlOutput("selectlevel2pred")))))),
                           
                   navbarMenu("Case Studies",
                              tabPanel("Varing-intercept",
                                       tabsetPanel(type="tabs",
                                                   tabPanel("Pooled Method",
                                                            column(6,
                                                                   plotOutput("poolednopredgraph")),
                                                            column(5,br(),br(),
                                                                   p("The", code("pooled method",style="color:navy"), "completely pools all level 1 observational units and ignores 
                                                                     that there is nesting in level 2 observational units.  Therefore, the pooled mean is the overall mean of the 
                                                                     response variable, not accounting for variability among the level 2 observational units in the response variable."),
                                                                     uiOutput("pooled.nopred.info")),
                                                            column(1)),
                                                   tabPanel("Unpooled Method",
                                                            column(6,
                                                                   plotOutput("unpooled.nopred.graph")),
                                                            column(5,br(),br(),
                                                                   p("The", code("unpooled method",style="color:navy"), "fits a separate average for each level 2 observational unit.  
                                                                     An issue is that the unpooled method exaggerates the variability in the response among the level 2 observational units because
                                                                     information across all level 2 observational units are ignored.  For example, some level 2 observational units 
                                                                     may have smaller sample size that would yield unreliable estimates with the pooled method.  However, this can
                                                                     be accounted for with hierarchical models."),
                                                                   tableOutput("unpooled.mod.summary")),
                                                            column(1),
                                                            column(12,hr(),br(),
                                                            dataTableOutput("unpooled.nopred.info"))),
                                                   tabPanel("Hierarchical Linear Model",
                                                            fluidRow(
                                                              column(5,
                                                                     bsCollapse(multiple=TRUE,open=c("hlmnopred1","hlmcat1"),id="hlmnopredcollapse2",
                                                                                bsCollapsePanel("Model Equation",id="hlmnopred1",
                                                                                                strong("Varying-intercept model:"),
                                                                                                p("$$y_i = \\alpha_{j[i]} + \\epsilon_i, where\\, \\epsilon_i \\sim N(0,\\sigma_y^{2})$$"),
                                                                                                p("$$\\alpha_j = \\mu_{\\alpha} + \\eta_j, where\\, \\eta_j \\sim N(0,\\sigma_\\alpha^{2})$$"),
                                                                                                checkboxInput("formdiff1","Unified equation",FALSE),
                                                                                                conditionalPanel(
                                                                                                  condition="input.formdiff1",
                                                                                                  p("$$y_i = \\mu_{\\alpha} + \\eta_j + \\epsilon_i$$"),
                                                                                                  p("$$\\epsilon_i \\sim N(0,\\sigma_y^{2})$$"),
                                                                                                  p("$$\\eta_j \\sim N(0,\\sigma_\\alpha^{2})$$")),
                                                                                                checkboxInput("discover","Explore equations",FALSE),
                                                                                                conditionalPanel(
                                                                                                  condition="input.discover",
                                                                                                  p("$$y_i = true\\,response\\,for\\,observational\\,unit\\,i$$"),
                                                                                                  p("$$\\alpha_{j[i]} = true\\,HLM\\,mean\\,of\\,group\\,j\\,for\\,observational\\,unit\\,i$$"),
                                                                                                  p("$$\\epsilon_i = deviation\\,of\\,observational\\,unit\\,i\\,from\\,its\\,group\\,average$$"),
                                                                                                  p("$$\\sigma_y^{2} = within\\,group\\,variance\\,in\\,response$$"),
                                                                                                  p("$$\\mu_{\\alpha} = true\\,average\\,of\\,group\\,averages$$"),
                                                                                                  p("$$\\eta_j = deviation\\,of\\,group\\,j\\,from\\,true\\,average$$"),
                                                                                                  p("$$\\sigma_\\alpha^{2} = between\\,group\\,variance\\,in\\,response$$"))),
                                                                                bsCollapsePanel("Caterpillar Plot",id="hlmcat1",
                                                                                                plotOutput("ggcat1")),
                                                                                bsCollapsePanel("Shrinkage of Estimates",id="hlmnopred2",
                                                                                                strong("Hierarchical weighted average for group j:"),
                                                                                                bsPopover("hlmnopred2","Interpretation","<li type=circle>A group with a smaller sample size will have a hierarchical estimate weighted less on their unpooled estimate and more on the pooled estimate.</li><li type=circle>More variability among the groups gives less weight on the pooled estimate.</li><li type=circle>More variability within the groups gives less weight on the unpooled estimates.</li>",
                                                                                                          trigger="hover",placement="top"),
                                                                                                p("$$\\hat{\\alpha}_j^{HLM} = \\hat{\\omega_j}*\\hat{\\mu}_\\alpha+(1-\\hat{\\omega_j})*\\bar{y}_j$$"),
                                                                                                p("$$\\hat{\\omega}_j = 1-\\frac{n_j*\\hat{\\sigma}_\\alpha^{2}}{n_j*\\hat{\\sigma}_\\alpha^{2}+\\hat{\\sigma}_y^{2}}$$"),
                                                                                                checkboxInput("discover1","Explore formula",FALSE),
                                                                                                conditionalPanel(
                                                                                                  condition="input.discover1",
                                                                                                  p("$$\\hat{\\omega}_j = pooling\\,factor$$"),
                                                                                                  p("$$n_j = sample\\,size\\,of\\,group\\,j$$"),
                                                                                                  p("$$\\hat{\\sigma}_y^{2} = within\\,group\\,(unexplained)\\,variance\\,in\\,response$$"),
                                                                                                  p("$$\\hat{\\sigma}_\\alpha^{2} = between\\,group\\,(explained)\\,variance\\,in\\,response$$"),
                                                                                                  p("$$\\bar{y}_{all} = pooled\\,mean$$"))),
                                                                                bsCollapsePanel("Distribution of Estimates",id="hlmnopred3",
                                                                                                strong("Distribution of HLM means:"),
                                                                                                p("$$\\alpha_j \\sim N(\\mu_{\\alpha},\\sigma_\\alpha^{2})$$"),
                                                                                                plotOutput("hlmdist1"),
                                                                                                withMathJax(),
                                                                                                uiOutput("hlmdistinfo1"),
                                                                                                checkboxInput("showdist11","Show distribution of group-level errors",FALSE),
                                                                                                conditionalPanel(
                                                                                                  condition="input.showdist11",
                                                                                                  plotOutput("hlmdisterror1"))),
                                                                                bsCollapsePanel("Intraclass Correlation Coefficient",id="hlmnopred4",
                                                                                                strong("Intraclass correlation coefficient:"),
                                                                                                bsPopover("hlmnopred4","Interpretation","The percentage of the variability in the response that is explained by the heterogeneity among groups.",
                                                                                                          trigger="hover",placement="top"),
                                                                                                withMathJax(),
                                                                                                uiOutput("intraclass1"),
                                                                                                checkboxInput("discover2","Explore formula",FALSE),
                                                                                                conditionalPanel(
                                                                                                  condition="input.discover2",
                                                                                                  p("$$\\hat{\\sigma}_y^{2} = within\\,group\\,(unexplained)\\,variance\\,in\\,response$$"),
                                                                                                  p("$$\\hat{\\sigma}_\\alpha^{2} = between\\,group\\,(explained)\\,variance\\,in\\,response$$")),
                                                                                                checkboxInput("calcicc1","Show ICC",FALSE),
                                                                                                conditionalPanel(
                                                                                                  condition="input.calcicc1",
                                                                                                  uiOutput("calcintraclass1"))),
                                                                                bsCollapsePanel("Ratio of variances",id="hlmnopred5",
                                                                                                strong("Ratio of variances:"),
                                                                                                bsPopover("hlmnopred5","Interpretation","<li type=circle> A group with a sample size less than this ratio will have a HLM mean closer to the pooled mean.</li> <li type=circle>A group with a sample size greater than this ratio will have a HLM mean closer to its unpooled mean.</li>",
                                                                                                          trigger="hover",placement="top"),
                                                                                                withMathJax(),
                                                                                                uiOutput("ratio1"),
                                                                                                checkboxInput("discover3","Explore formula",FALSE),
                                                                                                conditionalPanel(
                                                                                                  condition="input.discover3",
                                                                                                  p("$$\\hat{\\sigma}_y^{2} = within\\,group\\,(unexplained)\\,variance\\,in\\,response$$"),
                                                                                                  p("$$\\hat{\\sigma}_\\alpha^{2} = between\\,group\\,(explained)\\,variance\\,in\\,response$$")),
                                                                                                checkboxInput("calcratio1","Show ratio of variances",FALSE),
                                                                                                conditionalPanel(
                                                                                                  condition="input.calcratio1",
                                                                                                  uiOutput("calcratiovariances1"))))),
                                                              column(7,
                                                                     bsCollapse(multiple=TRUE,open=c("hlmnopred1"),id="hlmnopredcollapse1",
                                                                                bsCollapsePanel("HLM Output",id="hlmnopred1",
                                                                                                verbatimTextOutput("hlm.nopred1"),
                                                                                                checkboxInput("showconf1","Show confidence intervals",FALSE),
                                                                                                conditionalPanel(
                                                                                                  condition="input.showconf1",
                                                                                                  tableOutput("hlm.nopred2"))),
                                                                                bsCollapsePanel("HLM Estimates Table",id="hlmnopred10",
                                                                                                dataTableOutput("hlmtable")))))),
                                                   tabPanel("Comparison of Methods",
                                                            column(12,
                                                                   plotOutput("shrinkplot")),
                                                            column(12)),
                                                   tabPanel("Bayesian Hierarchical Linear Model",
                                                            column(6,
                                                                   plotOutput("postdist")),
                                                            column(6,
                                                                   verbatimTextOutput("hlm.bayes1")),
                                                            column(12)))),
                              tabPanel("Varying-intercept and varying-slope",
                                       tabsetPanel(type="tabs",
                                                   tabPanel("Pooled Method",
                                                            column(6,
                                                                   plotOutput("pooled.graph")),
                                                            column(4,
                                                                   br(),br(),
                                                                   tableOutput("pooled.output"),
                                                                   textOutput("pooled.info")),
                                                            column(2)),
                                                   tabPanel("Unpooled Method",
                                                            column(6,
                                                                   plotOutput("unpooled.graph")),
                                                            column(4,
                                                                   br(),br(),
                                                                   tableOutput("unpooled.output"),
                                                                   textOutput("unpooled.info")),
                                                            column(2),
                                                            column(12,hr(),br(),
                                                                   dataTableOutput("unpooled.est"))),
                                                   tabPanel("Hierarchical Linear Model",
                                                            fluidRow(
                                                              column(5,
                                                                     bsCollapse(multiple=TRUE,open=c("hlm1","hlm2","hlmcat2"),id="hlmcollapse1",
                                                                                bsCollapsePanel("HLM Model Equation",id="hlm1",
                                                                                                strong("Varying-intercept and varying-slope model:"),
                                                                                                p("$$y_i = \\alpha_{j[i]} + \\beta_{j[i]}x_i + \\epsilon_i$$"),
                                                                                                p("$$\\alpha_j = \\mu_{\\alpha} + \\eta^{\\alpha}_j$$"),
                                                                                                p("$$\\beta_j = \\mu_{\\beta} + \\eta^{\\beta}_j$$"),
                                                                                                p("$$\\begin{pmatrix} \\alpha_j \\\\ \\beta_j \\end{pmatrix} \\sim N\\begin{pmatrix} \\begin{pmatrix} \\mu_{\\alpha} \\\\ \\mu_{\\beta} \\end{pmatrix} , 
                                                                                                  \\begin{pmatrix} \\sigma_\\alpha^{2} & \\rho\\sigma_\\alpha\\sigma_\\beta \\\\ \\rho\\sigma_\\alpha\\sigma_\\beta & \\sigma_\\beta^{2} \\end{pmatrix} \\end{pmatrix}$$"),
                                                                                                br(),
                                                                                                p("Error terms:"),
                                                                                                p("$$\\epsilon_i \\sim N(0,\\sigma_y^{2})$$"),
                                                                                                p("$$\\begin{pmatrix} \\eta^{\\alpha}_j \\\\ \\eta^{\\beta}_j \\end{pmatrix} \\sim N\\begin{pmatrix} \\begin{pmatrix} 0 \\\\ 0 \\end{pmatrix} , 
                                                                                                  \\begin{pmatrix} \\sigma_\\alpha^{2} & \\rho\\sigma_\\alpha\\sigma_\\beta \\\\ \\rho\\sigma_\\alpha\\sigma_\\beta & \\sigma_\\beta^{2} \\end{pmatrix} \\end{pmatrix}$$")),
                                                                                bsCollapsePanel("HLM Graph",id="hlm2",
                                                                                                plotOutput("hlm.graph")),
                                                                                bsCollapsePanel("Caterpillar Plot",id="hlmcat2",
                                                                                                plotOutput("ggcat2")),
                                                                                bsCollapsePanel("HLM Distributions of Estimates",id="hlm3",
                                                                                                plotOutput("hlmparamdist1"),
                                                                                                checkboxInput("showhlmerror","Show distributions of group-level errors",FALSE),
                                                                                                conditionalPanel(
                                                                                                  condition="input.showhlmerror",
                                                                                                  plotOutput("hlmparamdist2"))))),
                                                                                                                 
                                                              column(7,
                                                                     bsCollapse(multiple=TRUE,open="hlm10",id="hlmcollapse2",
                                                                                bsCollapsePanel("HLM Output",id="hlm10",
                                                                                                verbatimTextOutput("hlm.summary"),
                                                                                                checkboxInput("showconf2","Show confidence intervals",FALSE),
                                                                                                conditionalPanel(
                                                                                                  condition="input.showconf2",
                                                                                                  tableOutput("hlm.confint1"))),
                                                                                bsCollapsePanel("HLM Estimates Table",id="hlm11",
                                                                                                dataTableOutput("hlm.est")))))),
                                                   tabPanel("Comparison of Methods",
                                                            fluidRow(
                                                              column(6,
                                                                     plotOutput("comp.method")),
                                                              column(6,
                                                                     plotOutput("slopeint.comp")))),
                                                   tabPanel("Bayesian Hierarchical Linear Model",
                                                            column(6,
                                                                   plotOutput("postdist2")),
                                                            column(6,
                                                                   verbatimTextOutput("hlm.bayes2")),
                                                            column(12)))),
                   
                   tabPanel("Varying-intercept and varying-slope with level 2 predictor",
                            tabsetPanel(type="tabs",
                                        tabPanel("Unpooled Method",
                                                 column(8,
                                                        plotOutput("stage2graph")),
                                                 column(4,
                                                        br(),
                                                        strong("Intercepts:"),
                                                        tableOutput("int.mod"),
                                                        br(),
                                                        strong("Slopes:"),
                                                        tableOutput("slope.mod")),
                                                 column(12)),
                                        tabPanel("Hierarchical Linear Model",
                                                 column(5,
                                                        bsCollapse(multiple=TRUE,open=c("hlm21","hlm22","hlmcat3"),id="hlmcollapse3",
                                                                   bsCollapsePanel("HLM Model Equation",id="hlm21",
                                                                                   strong("Varying-intercept and varying-slope with level 2 predictor model:"),
                                                                                   p("$$y_i = \\alpha_{j[i]} + \\beta_{j[i]}x_i + \\epsilon_i$$"),
                                                                                   p("$$\\alpha_j = \\gamma^{\\alpha}_0 + \\gamma^{\\alpha}_1\\mu_j + \\eta^{\\alpha}_j$$"),
                                                                                   p("$$\\beta_j = \\gamma^{\\beta}_0 + \\gamma^{\\beta}_1\\mu_j + \\eta^{\\beta}_j$$"),
                                                                                   p("$$\\begin{pmatrix} \\alpha_j \\\\ \\beta_j \\end{pmatrix} \\sim N\\begin{pmatrix} \\begin{pmatrix} \\gamma^{\\alpha}_0 + \\gamma^{\\alpha}_1\\mu_j \\\\ \\gamma^{\\beta}_0 + \\gamma^{\\beta}_1\\mu_j \\end{pmatrix} , 
                                                                                      \\begin{pmatrix} \\sigma_\\alpha^{2} & \\rho\\sigma_\\alpha\\sigma_\\beta \\\\ \\rho\\sigma_\\alpha\\sigma_\\beta & \\sigma_\\beta^{2} \\end{pmatrix} \\end{pmatrix}$$")),
                                                                   bsCollapsePanel("Caterpillar Plot",id="hlmcat3",
                                                                                   plotOutput("ggcat3")),
                                                                   bsCollapsePanel("HLM Hyperparameters",id="hlm22",
                                                                                   strong("Fixed effects"),
                                                                                   tableOutput("hlmhyper1"),br(),
                                                                                   strong("Random effects"),
                                                                                   verbatimTextOutput("hlmhyper2"),
                                                                                   checkboxInput("showconf3","Show confidence intervals",FALSE),
                                                                                   conditionalPanel(
                                                                                     condition="input.showconf3",
                                                                                     tableOutput("hlm.confint2"))))),
                                                 column(7,
                                                        bsCollapse(multiple=TRUE,open=c("hlm23","hlmcat3"),id="hlmcollapse4",
                                                                   bsCollapsePanel("HLM Output",id="hlm23",
                                                                                   verbatimTextOutput("hlm.summary1"))))),
                                        tabPanel("Comparison of Methods",
                                                 column(12,
                                                        plotOutput("compgraph")),
                                                 column(12))))),
                              

                   tabPanel("Analyze Data",
                            column(3,
                                   strong("Customize Model:"),
                                   htmlOutput("selectresponse.analyze"),
                                   htmlOutput("selectlevel2id.anaylze"),
                                   htmlOutput("selectlevel1pred.analyze"),
                                   htmlOutput("selectlevel1pred.analyze.rand"),
                                   htmlOutput("selectlevel2pred.analyze"),
                                   htmlOutput("selectcrosslevint"),
                                   actionButton("runmod",strong("Fit model"))),
                            column(9,
                                   bsCollapse(multiple=TRUE,open="hlmdata2",id="hlmanalyze",
                                              bsCollapsePanel("HLM Output",id="hlmdata2",
                                                              verbatimTextOutput("summary.analyze")))),
                            column(12))
        )
))
