# -----------------------------------------------------------------
# App Title: Performance of Wilcoxon-Mann-Whitney Test and t-test
#    Author: Jimmy Wong
# -----------------------------------------------------------------

if (!require("ggplot2")) install.packages("ggplot2")
if (!require("gridExtra")) install.packages("gridExtra")
if (!require("googleVis")) install.packages("googleVis")
if (!require("shinyBS")) install.packages("shinyBS")
if (!require("shinyIncubator")) install.packages("shinyIncubator")

shinyUI(fluidPage(
  tags$head(tags$link(rel = "icon", type = "image/x-icon", 
                      href = "https://webresource.its.calpoly.edu/cpwebtemplate/5.0.1/common/images_html/favicon.ico")),
  
  titlePanel("Performance of Wilcoxon-Mann-Whitney Test and t-test"),
  
  tabsetPanel(type="tabs",
              tabPanel("Goal of Study",
                       column(1),
                       column(4,
                              br(),br(),
                              p("This study compares the", span("Type I error rate",style = "color:red"), "and", span("power",style = "color:blue"), 
                                "between the two-sample t-test and the Wilcoxon-Mann-Whitney (WMW) test. The", strong("two-sample t-test"), "requires either the 
                                two population distributions to be normal or the sample sizes to be large enough in order for the sampling distribution 
                                to be normal.  The", strong("WMW test"), "is a nonparametric test that requires the two population distributions to have the same shape.
                                When two populations have the same mean, Type I error rate is of interest.  In contrast, when two populations have different 
                                means, power is of interest"),
                              p("Different scenarios are analyzed in this study, such as comparing two Normal distributions, a Normal to a Gamma distribution, and two Gamma 
                                distributions with small and large sample sizes.  The better test is determined either through a lower Type I error rate or a higher power.")),
                       column(6,
                              plotOutput("intrograph"),br(),
                              bsPopover("intrograph", "Note","These 4 graphs provide sample scenarios. In each of these sample scenarios, would you focus on Type I error rate or power?",
                                        placement="left",trigger="hover"),
                              div("Shiny app by", 
                                  a(href="http://www.linkedin.com/in/jimmywong46/",target="_blank","Jimmy Wong"),align="right", style = "font-size: 8pt"),
                              div("Base R code by", 
                                  a(href="http://www.linkedin.com/in/jimmywong46/",target="_blank","Jimmy Wong"),align="right", style = "font-size: 8pt"),
                              div("Shiny source files:",
                                  a(href="https://gist.github.com/calpolystat/8f525780393a05e7d0fd",
                                    target="_blank","GitHub Gist"),align="right", style = "font-size: 8pt"),
                              div(a(href="http://www.statistics.calpoly.edu/shiny",target="_blank", 
                                    "Cal Poly Statistics Dept Shiny Series"),align="right", style = "font-size: 8pt")),
                       column(1)),
              
              tabPanel("Guess the Population!",
                       column(1),
                       column(4,
                              br(),
                              p("It is time to", strong("Guess the Population!"), "This game demonstrates the difficulty of identifying which
                                pair of sample data are from the same population. Below are 4 histograms of randomly generated data with sample 
                                sizes of 20, where 2 are from", code("N(3,1)"), "(Normal distribution) and 2 are from", code("Gamma(6,.5)"), "(Gamma distribution)."),
                              div("Can you determine which pair came from the Normal distribution and which pair from the Gamma distribution?",style = "color:navy"),
                              tags$hr(),
                              uiOutput("answerinsert"),
                              uiOutput("answercheck"),br(),
                              uiOutput("answerreveal"),
                              conditionalPanel(
                                condition="input.reveal",
                                tableOutput("answer"))),
                       column(6,
                              plotOutput("guesspop"),
                              actionButton("resetgame", "Reset game"),
                              div("Shiny app by", 
                                  a(href="http://www.linkedin.com/in/jimmywong46/",target="_blank","Jimmy Wong"),align="right", style = "font-size: 8pt"),
                              div("Base R code by", 
                                  a(href="http://www.linkedin.com/in/jimmywong46/",target="_blank","Jimmy Wong"),align="right", style = "font-size: 8pt"),
                              div("Shiny source files:",
                                  a(href="https://gist.github.com/calpolystat/8f525780393a05e7d0fd",
                                    target="_blank","GitHub Gist"),align="right", style = "font-size: 8pt"),
                              div(a(href="http://www.statistics.calpoly.edu/shiny",target="_blank", 
                                    "Cal Poly Statistics Dept Shiny Series"),align="right", style = "font-size: 8pt")),
                       column(1)),
              
              navbarMenu("Two Normal Populations",
                                   tabPanel("Single comparison",
                                            fluidPage(
                                              absolutePanel(
                                                right=110,width=220,draggable=TRUE,cursor="move",
                                                wellPanel(
                                                  h5("Normal distribution 1:"),
                                                  sliderInput("nnorm1","Sample size:",min=10,max=100,step=10,value=20),
                                                  numericInput("meannorm1","Mean:",value=3),
                                                  tags$hr(),
                                                  h5("Normal distribution 2:"),
                                                  sliderInput("nnorm2","Sample size:",min=10,max=100,step=10,value=20),
                                                  numericInput("meannorm2","Mean:",value=4),
                                                  tags$hr(),
                                                  sliderInput("alpha1",HTML("Significance level &alpha;:"),min=.01,max=1,step=.01,value=.05),
                                                  sliderInput("nsim1","Number of simulations:",min=10,max=1000,value=50,step=10),br(),
                                                  actionButton("start1","Start simulation!"),
                                                  br(),br(),br(),
                                                  div("Shiny app by", 
                                                      a(href="http://www.linkedin.com/in/jimmywong46/",target="_blank","Jimmy Wong"),align="right", style = "font-size: 8pt"),
                                                  div("Base R code by", 
                                                      a(href="http://www.linkedin.com/in/jimmywong46/",target="_blank","Jimmy Wong"),align="right", style = "font-size: 8pt"),
                                                  div("Shiny source files:",
                                                      a(href="https://gist.github.com/calpolystat/8f525780393a05e7d0fd",
                                                        target="_blank","GitHub Gist"),align="right", style = "font-size: 8pt"),
                                                  div(a(href="http://www.statistics.calpoly.edu/shiny",target="_blank", 
                                                        "Cal Poly Statistics Dept Shiny Series"),align="right", style = "font-size: 8pt"))),
                                              column(8,
                                                     bsCollapse(multiple=TRUE, open=c("normnorm1","normnorm2","normcond"), id="normalcollapse",
                                                                bsCollapsePanel("Population Distributions", id="normnorm1",
                                                                                bsPopover("normnorm1","Collapsible!","Click to collapse.",trigger="hover",placement="top"),
                                                                                plotOutput("twonormplots"),
                                                                                uiOutput("normselected"),
                                                                                p("Note:"),
                                                                                HTML("<ol> <li type=circle> Variances are fixed at 1 </li>
                                                                                      <li type=circle> P(rejecting Ho | &mu;<sub>1</sub>=&mu;<sub>2</sub>) = Type I error rate
                                                                                      </li> <li type=circle> P(rejecting Ho | &mu;<sub>1</sub>&ne;&mu;<sub>2</sub>) = Power </li> </ol>"), br(),
                                                                                conditionalPanel(
                                                                                  condition="input.meannorm1==input.meannorm2",
                                                                                  div("These two Normal distributions have the same means; focus on", code("Type I error rate"),
                                                                                      style = "color:navy")),
                                                                                conditionalPanel(
                                                                                  condition="input.meannorm1!=input.meannorm2",
                                                                                  div("These two Normal distributions have different means; focus on", code("Power"),
                                                                                      style = "color:navy"))),
                                                                bsCollapsePanel("Conditions", id="normcond",
                                                                                bsPopover("normcond","Collapsible!","Click to collapse.",trigger="hover",placement="top"),
                                                                                uiOutput("satisfied1")),
                                                                bsCollapsePanel("Simulation Results", id="normnorm2",
                                                                                conditionalPanel(
                                                                                  condition="input.start1>0",
                                                                                  bsPopover("normnorm2","Collapsible!","Click to collapse.",trigger="hover",placement="top"),
                                                                                  plotOutput("twohistnorms"),
                                                                                  column(3,
                                                                                         #tableOutput("table1"),
                                                                                         conditionalPanel(
                                                                                           condition="input.meannorm1==input.meannorm2",
                                                                                           strong("Type I error rate:")),
                                                                                         conditionalPanel(
                                                                                           condition="input.meannorm1!=input.meannorm2",
                                                                                           strong("Power:")),
                                                                                         htmlOutput("gauge1")),
                                                                                  column(4,
                                                                                         br(),br(),
                                                                                         uiOutput("text1")))))),
                                              column(4))),
                                   
                                   tabPanel("Comparison over a range",
                                            fluidPage(
                                              absolutePanel(
                                                right=110,width=220,draggable=TRUE,cursor="move",
                                                     wellPanel(
                                                       h5("Normal distribution 1:"),
                                                       sliderInput("nnorm11","Sample size:",min=10,max=100,step=10,value=20),
                                                       sliderInput("varymeans1","Range of means:",min=-10,max=10,step=1,value=c(0,6)),
                                                       tags$hr(),
                                                       h5("Normal distribution 2:"),
                                                       sliderInput("nnorm21","Sample size:",min=10,max=100,step=10,value=20),
                                                       sliderInput("meannorm21","Mean:",min=-10,max=10,step=1,value=3),
                                                       tags$hr(),
                                                       sliderInput("alpha11",HTML("Significance level &alpha;:"),min=.01,max=1,step=.01,value=.05),
                                                       sliderInput("nsim11","Number of simulations:",min=10,max=200,value=50,step=10),br(),
                                                       actionButton("start11","Start simulation!"),
                                                       br(),br(),br(),
                                                       div("Shiny app by", 
                                                           a(href="http://www.linkedin.com/in/jimmywong46/",target="_blank","Jimmy Wong"),align="right", style = "font-size: 8pt"),
                                                       div("Base R code by", 
                                                           a(href="http://www.linkedin.com/in/jimmywong46/",target="_blank","Jimmy Wong"),align="right", style = "font-size: 8pt"),
                                                       div("Shiny source files:",
                                                           a(href="https://gist.github.com/calpolystat/8f525780393a05e7d0fd",
                                                             target="_blank","GitHub Gist"),align="right", style = "font-size: 8pt"),
                                                       div(a(href="http://www.statistics.calpoly.edu/shiny",target="_blank", 
                                                             "Cal Poly Statistics Dept Shiny Series"),align="right", style = "font-size: 8pt"))),
                                              column(8,
                                                     bsCollapse(multiple=TRUE, open=c("c11","c12"), id="normalvarycollapse",
                                                                bsCollapsePanel("Simulation Information", id="c11",
                                                                                bsPopover("c11","Collapsible!","Click to collapse.",trigger="hover",placement="top"),
                                                                                span("In this scenario, the mean of the 1st Normal distribution varies according to the specified range, while the mean of the
                                                                                     2nd Normal distribution remains constant.  The Type 1 error rate and power is compared between the t-test and the WMW test.",
                                                                                     style = "color:black")),
                                                                bsCollapsePanel("Simulation Results", id="c12",
                                                                                p("In the generated graph, each point is either a Type I error rate or power; 
                                                                                  there is at most 1 Type I error rate (when the two population means are the same)."),
                                                                                conditionalPanel(
                                                                                  condition="input.start11>0",
                                                                                  bsPopover("c12","Collapsible!","Click to collapse.",trigger="hover",placement="top"),
                                                                                  htmlOutput("graph.norm"))))),
                                              column(4)))),
                                      
              navbarMenu("Normal and Gamma Populations",
                         tabPanel("Single comparison",
                                  fluidPage(
                                    absolutePanel(
                                      right=110,width=220,draggable=TRUE,cursor="move",
                                      wellPanel(
                                        h5("Normal distribution:"),
                                        sliderInput("nnorm3","Sample size:",min=10,max=100,step=10,value=10),
                                        numericInput("meannorm3","Mean:",value=3),
                                        tags$hr(),
                                        h5("Gamma distribution:"),
                                        sliderInput("ngam1","Sample size:",min=10,max=100,step=10,value=10),
                                        sliderInput("shape1","Shape:",min=.5,max=20,step=.5,value=8),
                                        sliderInput("scale1","Scale:",min=.5,max=10,step=.5,value=.5),
                                        tags$hr(),
                                        sliderInput("alpha2",HTML("Significance level &alpha;:"),min=.01,max=1,step=.01,value=.05),
                                        sliderInput("nsim2","Number of simulations:",min=10,max=1000,value=50,step=10),br(),
                                        actionButton("start2","Start simulation!"),
                                        br(),br(),br(),
                                        div("Shiny app by", 
                                            a(href="http://www.linkedin.com/in/jimmywong46/",target="_blank","Jimmy Wong"),align="right", style = "font-size: 8pt"),
                                        div("Base R code by", 
                                            a(href="http://www.linkedin.com/in/jimmywong46/",target="_blank","Jimmy Wong"),align="right", style = "font-size: 8pt"),
                                        div("Shiny source files:",
                                            a(href="https://gist.github.com/calpolystat/8f525780393a05e7d0fd",
                                              target="_blank","GitHub Gist"),align="right", style = "font-size: 8pt"),
                                        div(a(href="http://www.statistics.calpoly.edu/shiny",target="_blank", 
                                              "Cal Poly Statistics Dept Shiny Series"),align="right", style = "font-size: 8pt"))),
                                    column(8,
                                           bsCollapse(multiple=TRUE, open=c("normgam1","normgam2","normgamcond"), id="normgamcollapse",
                                                      bsCollapsePanel("Population Distributions", id="normgam1",
                                                                      bsPopover("normgam1","Collapsible!","Click to collapse.",trigger="hover",placement="top"),
                                                                      plotOutput("twonormgamplots"),
                                                                      uiOutput("normgamselected"),
                                                                      p("Note:"),
                                                                      HTML("<ol> <li type=circle> Variance of Normal is fixed at 1 </li>
                                                                            <li type=circle> Gamma mean is the product of shape and scale </li>
                                                                            <li type=circle> P(rejecting Ho | &mu;<sub>1</sub>=&mu;<sub>2</sub>) = Type I error rate
                                                                            </li> <li type=circle> P(rejecting Ho | &mu;<sub>1</sub>&ne;&mu;<sub>2</sub>) = Power </li> </ol>"),br(),
                                                                      uiOutput("focusinfo1")),
                                                      bsCollapsePanel("Conditions", id="normgamcond",
                                                                      bsPopover("normgamcond","Collapsible!","Click to collapse.",trigger="hover",placement="top"),
                                                                      uiOutput("satisfied2")),
                                                      bsCollapsePanel("Simulation Results", id="normgam2",
                                                                      conditionalPanel(
                                                                        condition="input.start2>0",
                                                                        bsPopover("normgam2","Collapsible!","Click to collapse.",trigger="hover",placement="top"),
                                                                        plotOutput("twohistnormgams"),
                                                                        column(3,
                                                                               #tableOutput("table2"),
                                                                               uiOutput("whichone"),
                                                                               htmlOutput("gauge2")),
                                                                        column(4,
                                                                               br(),br(),
                                                                               uiOutput("text2")))))),
                                    column(4))),
                         tabPanel("Comparison over a range",
                                  fluidPage(
                                    absolutePanel(
                                      right=110,width=220,draggable=TRUE,cursor="move",
                                           wellPanel(
                                             h5("Normal distribution:"),
                                             sliderInput("nnorm31","Sample size:",min=10,max=100,step=10,value=20),
                                             sliderInput("varymeans2","Range of means:",min=0,max=50,step=1,value=c(0,6)),
                                             tags$hr(),
                                             h5("Gamma distribution:"),
                                             sliderInput("ngam11","Sample size:",min=10,max=100,step=10,value=20),
                                             sliderInput("shape11","Shape:",min=.5,max=10,step=.5,value=6),
                                             sliderInput("scale11","Scale:",min=.5,max=2.5,step=.5,value=.5),
                                             tags$hr(),
                                             sliderInput("alpha21",HTML("Significance level &alpha;:"),min=.01,max=1,step=.01,value=.05),
                                             sliderInput("nsim21","Number of simulations:",min=10,max=200,value=50,step=10),br(),
                                             actionButton("start21","Start simulation!"),
                                             br(),br(),br(),
                                             div("Shiny app by", 
                                                 a(href="http://www.linkedin.com/in/jimmywong46/",target="_blank","Jimmy Wong"),align="right", style = "font-size: 8pt"),
                                             div("Base R code by", 
                                                 a(href="http://www.linkedin.com/in/jimmywong46/",target="_blank","Jimmy Wong"),align="right", style = "font-size: 8pt"),
                                             div("Shiny source files:",
                                                 a(href="https://gist.github.com/calpolystat/8f525780393a05e7d0fd",
                                                   target="_blank","GitHub Gist"),align="right", style = "font-size: 8pt"),
                                             div(a(href="http://www.statistics.calpoly.edu/shiny",target="_blank", 
                                                   "Cal Poly Statistics Dept Shiny Series"),align="right", style = "font-size: 8pt"))),
                                    column(8,
                                           bsCollapse(multiple=TRUE, open=c("c21","c22"), id="normalvarycollapse",
                                                      bsCollapsePanel("Simulation Information", id="c21",
                                                                      bsPopover("c21","Collapsible!","Click to collapse.",trigger="hover",placement="top"),
                                                                      span("In this scenario, the mean of the Normal distribution varies according to the specified range, while the mean of the
                                                                           Gamma distribution remains constant.  The Type 1 error rate and power is compared between the t-test and the WMW test.",
                                                                           style = "color:black")),
                                                      bsCollapsePanel("Simulation Results", id="c22",
                                                                      p("In the generated graph, each point is either a Type I error rate or power; 
                                                                        there is at most 1 Type I error rate (when the two population means are the same)."),
                                                                      conditionalPanel(
                                                                        condition="input.start21>0",
                                                                        bsPopover("c22","Collapsible!","Click to collapse.",trigger="hover",placement="top"),
                                                                        htmlOutput("graph.normgam"))))),
                                    column(4)))),
                                    
              navbarMenu("Two Gamma Populations",
                         tabPanel("Single comparison",
                                  fluidPage(
                                    absolutePanel(
                                      right=110,width=220,draggable=TRUE,cursor="move",
                                      wellPanel(
                                        h5("Gamma distribution 1:"),
                                        sliderInput("ngam2","Sample size:",min=10,max=100,step=10,value=10),
                                        sliderInput("shape2","Shape:",min=.5,max=20,step=.5,value=6),
                                        sliderInput("scale2","Scale:",min=.5,max=10,step=.5,value=.5),
                                        tags$hr(),
                                        h5("Gamma distribution 2:"),
                                        sliderInput("ngam3","Sample size:",min=10,max=100,step=10,value=10),br(),
                                        sliderInput("far1","Distance from first Gamma:",min=0,max=100,step=1,value=3),
                                        tags$hr(),
                                        sliderInput("alpha3",HTML("Significance level &alpha;:"),min=.01,max=1,step=.01,value=.05),
                                        sliderInput("nsim3","Number of simulations:",min=10,max=1000,value=50,step=10),br(),
                                        actionButton("start3","Start simulation!"),
                                        br(),br(),br(),
                                        div("Shiny app by", 
                                            a(href="http://www.linkedin.com/in/jimmywong46/",target="_blank","Jimmy Wong"),align="right", style = "font-size: 8pt"),
                                        div("Base R code by", 
                                            a(href="http://www.linkedin.com/in/jimmywong46/",target="_blank","Jimmy Wong"),align="right", style = "font-size: 8pt"),
                                        div("Shiny source files:",
                                            a(href="https://gist.github.com/calpolystat/8f525780393a05e7d0fd",
                                              target="_blank","GitHub Gist"),align="right", style = "font-size: 8pt"),
                                        div(a(href="http://www.statistics.calpoly.edu/shiny",target="_blank", 
                                              "Cal Poly Statistics Dept Shiny Series"),align="right", style = "font-size: 8pt"))),
                                    column(8,
                                           bsCollapse(multiple=TRUE, open=c("gamgam1","gamgam2","gamcond"), id="gamgamcollapse",
                                                      bsCollapsePanel("Population Distributions", id="gamgam1",
                                                                      bsPopover("gamgam1","Collapsible!","Click to collapse.",trigger="hover",placement="top"),
                                                                      plotOutput("twogamplots"),
                                                                      uiOutput("gamselected"),
                                                                      p("Note:"),
                                                                      HTML("<ol> <li type=circle> Gamma mean is the product of shape and scale </li>
                                                                            <li type=circle> P(rejecting Ho | &mu;<sub>1</sub>=&mu;<sub>2</sub>) = Type I error rate
                                                                            </li> <li type=circle> P(rejecting Ho | &mu;<sub>1</sub>&ne;&mu;<sub>2</sub>) = Power </li> </ol>"),br(),
                                                                      uiOutput("focusinfo2")),
                                                      bsCollapsePanel("Conditions", id="gamcond",
                                                                      bsPopover("gamcond","Collapsible!","Click to collapse.",trigger="hover",placement="top"),
                                                                      uiOutput("satisfied3")),
                                                      bsCollapsePanel("Simulation Results", id="gamgam2",
                                                                      conditionalPanel(
                                                                        condition="input.start3>0",
                                                                        bsPopover("gamgam2","Collapsible!","Click to collapse.",trigger="hover",placement="top"),
                                                                        plotOutput("twohistgams"),
                                                                        column(3,
                                                                               #tableOutput("table3"),
                                                                               uiOutput("type1powertext"),
                                                                               htmlOutput("gauge3")),
                                                                        column(4,
                                                                               br(),br(),
                                                                               uiOutput("text3")))))),
                                    column(4))),
                         tabPanel("Comparison over a range",
                                  absolutePanel(
                                    right=110,width=220,draggable=TRUE,cursor="move",
                                           wellPanel(
                                             h5("Gamma distribution 1:"),
                                             sliderInput("ngam21","Sample size:",min=10,max=100,step=10,value=20),
                                             sliderInput("shape21","Shape:",min=.5,max=20,step=.5,value=12),
                                             sliderInput("scale21","Scale:",min=.5,max=10,step=.5,value=.5),
                                             tags$hr(),
                                             h5("Gamma distribution 2:"),
                                             sliderInput("ngam31","Sample size:",min=10,max=100,step=10,value=20),
                                             sliderInput("far2","Range of distance from first Gamma:",min=0,max=20,step=1,value=c(0,6)),
                                             tags$hr(),
                                             sliderInput("alpha31",HTML("Significance level &alpha;:"),min=.01,max=1,step=.01,value=.05),
                                             sliderInput("nsim31","Number of simulations:",min=10,max=200,value=50,step=10),br(),
                                             actionButton("start31","Start simulation!"),
                                             br(),br(),br(),
                                             div("Shiny app by", 
                                                 a(href="http://www.linkedin.com/in/jimmywong46/",target="_blank","Jimmy Wong"),align="right", style = "font-size: 8pt"),
                                             div("Base R code by", 
                                                 a(href="http://www.linkedin.com/in/jimmywong46/",target="_blank","Jimmy Wong"),align="right", style = "font-size: 8pt"),
                                             div("Shiny source files:",
                                                 a(href="https://gist.github.com/calpolystat/8f525780393a05e7d0fd",
                                                   target="_blank","GitHub Gist"),align="right", style = "font-size: 8pt"),
                                             div(a(href="http://www.statistics.calpoly.edu/shiny",target="_blank", 
                                                   "Cal Poly Statistics Dept Shiny Series"),align="right", style = "font-size: 8pt"))),
                                    column(8,
                                           bsCollapse(multiple=TRUE, open=c("c31","c32"), id="gammavarycollapse",
                                                      bsCollapsePanel("Simulation Information", id="c31",
                                                                      bsPopover("c31","Collapsible!","Click to collapse.",trigger="hover",placement="top"),
                                                                      span("In this scenario, the mean of the 1st Gamma distribution remains constant, while the mean of the 2nd
                                                                           Gamma distribution varies depending on the specified range of distance.  The Type 1 error rate and power 
                                                                           is compared between the t-test and the WMW test.",
                                                                           style = "color:black")),
                                                      bsCollapsePanel("Simulation Results", id="c32",
                                                                      p("In the generated graph, each point is either a Type I error rate or power; 
                                                                        there is at most 1 Type I error rate (when the two population means are the same)."),
                                                                      conditionalPanel(
                                                                        condition="input.start31>0",
                                                                        bsPopover("c32","Collapsible!","Click to collapse.",trigger="hover",placement="top"),
                                                                        htmlOutput("graph.gamgam"))))),
                                    column(3))))
  
))
